-- 2026-06-14 楼盘 pin 重设计:写楼盘图层样式行(ViewEntityStyle 期房底 + 现房/二手 ViewStyleRule + 条件)。
-- 幂等:重跑结果一致。前置:app 关闭、库已备份。
-- Core Data: ViewStyleRule Z_ENT=20、ViewStyleCondition Z_ENT=19;UUID 列=16-byte blob(randomblob(16));
-- 时间=自 2001 秒(strftime('%s','now')-978307200);ZVALUELIST 复制现有空数组归档 blob。
-- 前置条件:库内须已存在至少一条 ZVALUELIST 非空的条件(学校 StyleRule 条件)供步骤 5/6 子查询复制;
--   否则 ZVALUELIST 会插成 NULL(本机库有学校 3 条条件,成立)。
BEGIN;

-- 1. 幂等清理:删楼盘图层现有条件 + 规则(首次 0 条)
DELETE FROM ZVIEWSTYLECONDITION
 WHERE ZRULEID IN (
   SELECT ZID FROM ZVIEWSTYLERULE
   WHERE ZLAYERID = (SELECT ZID FROM ZLAYER WHERE ZNAME='楼盘' AND ZDELETED=0 LIMIT 1)
 );
DELETE FROM ZVIEWSTYLERULE
 WHERE ZLAYERID = (SELECT ZID FROM ZLAYER WHERE ZNAME='楼盘' AND ZDELETED=0 LIMIT 1);

-- 2. 楼盘图层 ViewEntityStyle = 期房底样式(UPDATE 既有行)
UPDATE ZVIEWENTITYSTYLE
 SET ZSHAPE='circle', ZFILLHEX='#0A84FF', ZSTROKEHEX='#FFFFFF',
     ZGLYPH='期', ZGLYPHHEX='#FFFFFF', ZSIZE=24, ZLABELVISIBLE=1,
     ZUPDATEDAT=(strftime('%s','now')-978307200)
 WHERE ZLAYERID=(SELECT ZID FROM ZLAYER WHERE ZNAME='楼盘' AND ZDELETED=0 LIMIT 1)
   AND ZDELETED=0;

-- 3. 现房规则(priority 10):绿 + 现
INSERT INTO ZVIEWSTYLERULE
 (Z_ENT,Z_OPT,ZDELETED,ZENABLED,ZLABELVISIBLE,ZPRIORITY,ZSIZE,ZVERSION,
  ZCREATEDAT,ZFILLOPACITY,ZSTROKEWIDTH,ZUPDATEDAT,
  ZENTITYTYPE,ZFILLHEX,ZGLYPH,ZGLYPHHEX,ZSHAPE,ZSTROKEHEX,ZDATASETID,ZID,ZLAYERID)
 VALUES
 (20,1,0,1,NULL,10,NULL,1,
  (strftime('%s','now')-978307200),NULL,NULL,(strftime('%s','now')-978307200),
  'compound','#34C759','现','#FFFFFF',NULL,NULL,
  (SELECT ZDATASETID FROM ZLAYER WHERE ZNAME='楼盘' AND ZDELETED=0 LIMIT 1),
  randomblob(16),
  (SELECT ZID FROM ZLAYER WHERE ZNAME='楼盘' AND ZDELETED=0 LIMIT 1));

-- 4. 二手规则(priority 20):黄 + 二(深字)
INSERT INTO ZVIEWSTYLERULE
 (Z_ENT,Z_OPT,ZDELETED,ZENABLED,ZLABELVISIBLE,ZPRIORITY,ZSIZE,ZVERSION,
  ZCREATEDAT,ZFILLOPACITY,ZSTROKEWIDTH,ZUPDATEDAT,
  ZENTITYTYPE,ZFILLHEX,ZGLYPH,ZGLYPHHEX,ZSHAPE,ZSTROKEHEX,ZDATASETID,ZID,ZLAYERID)
 VALUES
 (20,1,0,1,NULL,20,NULL,1,
  (strftime('%s','now')-978307200),NULL,NULL,(strftime('%s','now')-978307200),
  'compound','#FFCC00','二','#4A3B00',NULL,NULL,
  (SELECT ZDATASETID FROM ZLAYER WHERE ZNAME='楼盘' AND ZDELETED=0 LIMIT 1),
  randomblob(16),
  (SELECT ZID FROM ZLAYER WHERE ZNAME='楼盘' AND ZDELETED=0 LIMIT 1));

-- 5. 现房条件:deliveryTime contains 现房
INSERT INTO ZVIEWSTYLECONDITION
 (Z_ENT,Z_OPT,ZDELETED,ZSORTORDER,ZCREATEDAT,ZUPDATEDAT,
  ZFIELD,ZOP,ZVALUESTRING,ZID,ZRULEID,ZVALUELIST)
 VALUES
 (19,1,0,0,(strftime('%s','now')-978307200),(strftime('%s','now')-978307200),
  'deliveryTime','contains','现房',randomblob(16),
  (SELECT ZID FROM ZVIEWSTYLERULE WHERE ZPRIORITY=10 AND ZENTITYTYPE='compound'
     AND ZLAYERID=(SELECT ZID FROM ZLAYER WHERE ZNAME='楼盘' AND ZDELETED=0 LIMIT 1) LIMIT 1),
  (SELECT ZVALUELIST FROM ZVIEWSTYLECONDITION WHERE ZVALUELIST IS NOT NULL LIMIT 1));

-- 6. 二手条件:isNewHouse equals false
INSERT INTO ZVIEWSTYLECONDITION
 (Z_ENT,Z_OPT,ZDELETED,ZSORTORDER,ZCREATEDAT,ZUPDATEDAT,
  ZFIELD,ZOP,ZVALUESTRING,ZID,ZRULEID,ZVALUELIST)
 VALUES
 (19,1,0,0,(strftime('%s','now')-978307200),(strftime('%s','now')-978307200),
  'isNewHouse','equals','false',randomblob(16),
  (SELECT ZID FROM ZVIEWSTYLERULE WHERE ZPRIORITY=20 AND ZENTITYTYPE='compound'
     AND ZLAYERID=(SELECT ZID FROM ZLAYER WHERE ZNAME='楼盘' AND ZDELETED=0 LIMIT 1) LIMIT 1),
  (SELECT ZVALUELIST FROM ZVIEWSTYLECONDITION WHERE ZVALUELIST IS NOT NULL LIMIT 1));

-- 7. 同步 Z_PRIMARYKEY.Z_MAX(防 Core Data 下次分配 Z_PK 冲突)
UPDATE Z_PRIMARYKEY SET Z_MAX=(SELECT MAX(Z_PK) FROM ZVIEWSTYLERULE) WHERE Z_NAME='ViewStyleRule';
UPDATE Z_PRIMARYKEY SET Z_MAX=(SELECT MAX(Z_PK) FROM ZVIEWSTYLECONDITION) WHERE Z_NAME='ViewStyleCondition';

COMMIT;

-- 8. 把 WAL 折叠进主库,避免 -wal/-shm 残留与 app 不一致
PRAGMA wal_checkpoint(TRUNCATE);
